[features]
seeds = false
[programs.devnet]
solana_twitter_v1 = "6qjoZbo7CcNq3bfL8kVva7K6zPjoamdPjWQRhrVYaD6y"
solana_twitter_v2 = "J6CQfWfnsg7XCUAYYwHmUB6PMzH9wrvepGx8JnXv8mp6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-v1 = "cp ./target/idl/solana_twitter_v1.json ./app_v1/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter-v1.ts"
test-v2 = "cp ./target/idl/solana_twitter_v2.json ./app_v2/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter-v2.ts"
