[features]
seeds = false
[programs.devnet]
solana_twitter = "2ZBJqi4BrKY5JisDGG8zZHYazLErxCiMmVXABgDf31q2"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cp ./target/idl/solana_twitter.json ./app/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter.ts"
