[features]
seeds = false
[programs.localnet]
solana_twitter = "3ndBQedcoFTScsVJ8vNSHKpmh8UQQYMYQovqqnWPUbiK"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cp ./target/idl/solana_twitter.json ./app/src/utils/idl.json && yarn run ts-mocha -p ./tests/tsconfig.tests.json -t 1000000 tests/solana-twitter.ts"
