[features]
seeds = false
[programs.devnet]
emoji_exchange = "86GDPzi1UcCP91Ruvn2CJxSZnbwjmptn5ikKJAiqubyP"
voting_program = "2cXGBhMQmtDzQdPitek7CaJKXwZmcehVc6FpiovtKsQq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test-emoji-exchange = "cp ./target/idl/emoji_exchange.json ./app/src/utils/idl.json && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/emoji-exchange.ts"
test-voting-program = "cp ./target/idl/voting_program.json ./app/src/utils/idl.json && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/voting-program.ts"
